/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package kotlinhello

object App {
    val greeting: String
        get() {
            return "Hello world."
        }

    @JvmStatic
    fun main(args: Array<String>) {
        println(greeting)
    }

}

